Repository sermant-io/Sermant-website, pull requests merged in 2023-01, with the labels that each got.

#21 update doc for sermant-injector
  docs/en/document/user-guide/injector.md
  docs/zh/document/user-guide/injector.md
Labels: enhancement

#38 【doc】修改注册插件文档
  docs/en/document/plugin/registry/README.md
  docs/en/document/plugin/registry/dubbo-registry-migiration.md
  docs/en/document/plugin/registry/spring-cloud-registry-migiration.md
  docs/en/document/user-guide/sermant-agent.md
  docs/zh/document/plugin/registry/README.md
  docs/zh/document/plugin/registry/dubbo-registry-migiration.md
  docs/zh/document/plugin/registry/spring-cloud-registry-migiration.md
  docs/zh/document/user-guide/sermant-agent.md
Labels: documentation

#33 【doc】修改路由插件文档
  docs/en/document/plugin/router.md
  docs/zh/document/plugin/router.md
Labels: documentation

#39 【doc】修改链接
  docs/en/document/plugin/registry/spring-cloud-registry-migiration.md
  docs/en/document/plugin/router.md
  docs/zh/document/plugin/registry/spring-cloud-registry-migiration.md
  docs/zh/document/plugin/router.md
Labels: documentation

#45 【doc】sermant用户手册文档更新
  docs/.vuepress/public/docs-img/sermant-arch.png
  docs/en/document/user-guide/backend.md
  docs/en/document/user-guide/configuration-center.md
  docs/en/document/user-guide/injector.md
  docs/en/document/user-guide/readme.md
  docs/en/document/user-guide/sermant-agent.md
  docs/zh/document/user-guide/backend.md
  docs/zh/document/user-guide/configuration-center.md
  docs/zh/document/user-guide/injector.md
  docs/zh/document/user-guide/readme.md
  docs/zh/document/user-guide/sermant-agent.md
Labels: documentation, lgtm

#48 【doc】修改文档
  docs/.vuepress/public/docs-img/loadbanlance1.png
  docs/.vuepress/public/docs-img/loadbanlance2.png
  docs/.vuepress/public/docs-img/monitor.png
  docs/.vuepress/public/docs-img/visibility-consanguinity.png
  docs/.vuepress/public/docs-img/visibility-contarct.png
  docs/en/document/plugin/loadbalancer.md
  docs/en/document/plugin/monitor.md
  docs/en/document/plugin/visibility.md
  docs/zh/document/plugin/loadbalancer.md
  docs/zh/document/plugin/monitor.md
  docs/zh/document/plugin/visibility.md
Labels: documentation, lgtm

#46 【doc】开发者手册中文版修改
  docs/.vuepress/config.js
  docs/zh/document/developer-guide/README.md
  docs/zh/document/developer-guide/bytecode-enhancement.md
  docs/zh/document/developer-guide/dynamic-config-func.md
  docs/zh/document/developer-guide/heartbeat-func.md
  docs/zh/document/developer-guide/log-func.md
  docs/zh/document/developer-guide/package-structure.md
  docs/zh/document/developer-guide/plugin-configuration.md
  docs/zh/document/developer-guide/plugin/README.md
  docs/zh/document/developer-guide/third-party-copyright.md
  docs/zh/document/developer-guide/trace-tracking-func.md
  docs/zh/document/developer-guide/version-manage.md
Labels: documentation, lgtm

#52 【doc】修改创建首个插件时的mvn指令
  docs/zh/document/developer-guide/README.md
Labels: documentation

#49 【doc】修改文档
  docs/.vuepress/public/docs-img/dubbo-migration-en.png
  docs/.vuepress/public/docs-img/dubbo-migration.png
  docs/.vuepress/public/docs-img/registry-result-en.png
  docs/.vuepress/public/docs-img/registry-result.png
  docs/.vuepress/public/docs-img/router-result.png
  docs/.vuepress/public/docs-img/springcloud-migration-1.png
  docs/.vuepress/public/docs-img/springcloud-migration-2.png
  docs/.vuepress/public/docs-img/springcloud-migration-3.png
  docs/.vuepress/public/docs-img/springcloud-migration-4-en.png
  docs/.vuepress/public/docs-img/springcloud-migration-4.png
  docs/en/document/plugin/README.md
  docs/en/document/plugin/registry/README.md
  docs/en/document/plugin/router.md
  docs/zh/document/plugin/README.md
  docs/zh/document/plugin/registry/README.md
  docs/zh/document/plugin/router.md
Labels: documentation

#57 【doc】修改文档
  docs/.vuepress/public/docs-img/springboot-registry.png
  docs/en/document/plugin/registry/README.md
  docs/en/document/plugin/registry/springboot-registry.md
  docs/en/document/plugin/router.md
  docs/zh/document/plugin/registry/README.md
  docs/zh/document/plugin/registry/springboot-registry.md
  docs/zh/document/plugin/router.md
Labels: documentation

#51 更新文档
  docs/.vuepress/public/docs-img/dynamic-config-create-node-1.jpg
  docs/.vuepress/public/docs-img/dynamic-config-create-node-2.jpg
  docs/.vuepress/public/docs-img/dynamic-config-old-config.jpg
  docs/.vuepress/public/docs-img/dynamic-config-verify.jpg
  docs/.vuepress/public/docs-img/flowcontrol-create-node-1.jpg
  docs/.vuepress/public/docs-img/flowcontrol-create-node-2.jpg
  docs/.vuepress/public/docs-img/flowcontrol-create-node-3.jpg
  docs/.vuepress/public/docs-img/flowcontrol-verity.jpg
  docs/zh/document/plugin/dynamic-config.md
  docs/zh/document/plugin/flowcontrol.md
Labels: documentation

#67 update docs
  docs/zh/document/plugin/dynamic-config.md
  docs/zh/document/plugin/flowcontrol.md
Labels: documentation, lgtm

#66 【doc】修改标签路由插件文档
  docs/.vuepress/config.js
  docs/en/document/FAQ/framework.md
  docs/en/document/FAQ/registry.md
  docs/en/document/plugin/README.md
  docs/en/document/plugin/router.md
  docs/en/document/plugin/service-registry.md
  docs/en/document/plugin/springboot-registry.md
  docs/zh/document/FAQ/framework.md
  docs/zh/document/FAQ/registry.md
  docs/zh/document/plugin/README.md
  docs/zh/document/plugin/registry/springboot-registry.md
  docs/zh/document/plugin/router.md
  docs/zh/document/plugin/service-registry.md
  docs/zh/document/plugin/springboot-registry.md
Labels: documentation, lgtm
