Repository sermant-io/Sermant-website, pull requests merged in 2023-03, with the labels that each got.

#93 修改链路功能
  docs/zh/document/developer-guide/README.md
  docs/zh/document/developer-guide/package-structure.md
  docs/zh/document/developer-guide/trace-tracking-func.md
Labels: documentation, lgtm

#100 主页中心增加博客按钮
  docs/.vuepress/components/HomePage.vue
  docs/en/README.md
  docs/en/blog/README.md
  docs/zh/README.md
  docs/zh/blog/README.md
Labels: documentation, enhancement, lgtm

#101 主页增加页脚信息
  docs/.vuepress/components/HomePage.vue
  docs/.vuepress/public/img/contact-wechat.jpg
  docs/en/README.md
  docs/zh/README.md
Labels: enhancement, lgtm

#102 fix words
  docs/en/README.md
Labels: documentation, enhancement, lgtm

#103 update logo
  docs/.vuepress/components/HomePage.vue
  docs/.vuepress/public/img/sermant-logo.png
Labels: documentation, enhancement, lgtm
